import tensorflow as tf

class Model(tf.keras.Model):

    def __init__(self, vocab_size):
        super().__init__()

        embed_size = 64
        rnn_size = 64
        self.embedding1 = tf.keras.layers.Embedding(vocab_size, embed_size, mask_zero = True)
        self.embedding2 = tf.keras.layers.Embedding(vocab_size, embed_size, mask_zero = True)
        self.embedding3 = tf.keras.layers.Embedding(vocab_size, embed_size, mask_zero = True)
        self.gru1 = tf.keras.layers.GRU(rnn_size)
        self.gru2 = tf.keras.layers.GRU(rnn_size)
        self.gru3 = tf.keras.layers.GRU(rnn_size)
        self.softmax_dense1 = tf.keras.layers.Dense(2, activation="softmax")
        self.softmax_dense2 = tf.keras.layers.Dense(2, activation="softmax")
        self.softmax_dense3 = tf.keras.layers.Dense(2, activation="softmax")
        self.relu_dense1 = tf.keras.layers.Dense(2, activation=tf.keras.layers.LeakyReLU(alpha=0.3))
        self.relu_dense2 = tf.keras.layers.Dense(2, activation=tf.keras.layers.LeakyReLU(alpha=0.3))

    def call(self, inputs): # Inputs in format (sentiment words, non-sentiment words, all text)
        sent_words = inputs[0]
        non_sent_words = inputs[1]
        all_text = inputs[2]

        embedded_sent = self.embedding1(sent_words)
        embedded_non_sent = self.embedding2(non_sent_words)
        embedded_all = self.embedding3(all_text)
        
        encoded_sent = self.gru1(embedded_sent)
        encoded_non_sent = self.gru2(embedded_non_sent)
        encoded_all = self.gru3(embedded_all)

        lit_pred = self.softmax_dense1(encoded_sent)
        imp_pred = self.softmax_dense2(encoded_non_sent) # Literal and implied channel sentiment preds generated by running dense layer on encoded sentiment and non-sentiment words

        combined_lit_all = tf.concat([encoded_sent, encoded_all], axis = 1)
        combined_imp_all = tf.concat([encoded_non_sent, encoded_all], axis = 1)
        combined_lit_all = self.relu_dense1(combined_lit_all)
        combined_imp_all = self.relu_dense2(combined_imp_all)
        combined_channels = tf.concat([combined_lit_all, combined_imp_all], axis = 1)
        sarc_pred = self.softmax_dense3(combined_channels) # Sarcasm prediction generated by running dense layer on the combination of both channels' outputs.

        return (lit_pred, imp_pred, sarc_pred)
